theme = "max_monokai_pro_spectrum_no_underline"
# theme = "max_catppuccin_latte"

[editor]
cursorline = true
mouse = true
true-color = true
scrolloff = 17 
auto-format = true
# line-number = "relative"
auto-save = true
gutters = ["diff","diagnostics", "line-numbers", "spacer", "spacer"]
# gutters = ["diff","diagnostics", "spacer"]
jump-label-alphabet = "dlavmcfeiruwotybns;jk234789"
completion-timeout = 0
completion-trigger-len = 1
auto-pairs = false
bufferline = "never"

[editor.search]
wrap-around = false

[editor.lsp]
auto-signature-help = false
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.inline-diagnostics]
# cursor-line = "hint"
cursor-line = "disable"

[editor.smart-tab]
enable = true
supersede-menu = true

# [editor.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# '`' = '`'
# '<' = '>'

[keys.normal.m]
f = "select_regex"
F = "split_selection"
x = "join_selections"
# Match in next instance of pair
"(" = "@/\\(<ret>mi("
"{" = "@/\\{<ret>mi{"
"[" = "@/\\[<ret>mi["
'"' = '@/"<ret>lmi"'
"'" = "@/'<ret>lmi'"
"<" = "@/<lt><ret>mi<lt>"

# Match in previous instance of pair
[keys.normal.m.p]
"(" = "@/\\(<ret>NNmi("
"{" = "@/\\{<ret>NNmi{"
"[" = "@/\\[<ret>NNmi["
'"' = '@/"<ret>NNhmi"'
"'" = "@/'<ret>NNhmi'"
"<" = "@/<lt><ret>NNmi<lt>"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
# ignore = false
git-ignore = false
# git-global = false
git-exclude = false

[editor.indent-guides]
render = true

[editor.statusline]
right = [ "spinner", "position" ]
center = [ "file-name" ]
left = [ "mode" ]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = " │ "

[keys.normal]
A-t = ":wqa!"
A-b = ":qa!"
esc = ["collapse_selection", "keep_primary_selection"]
A-f = ["select_mode", "goto_line_end","extend_line_below", "delete_selection", "paste_after"]
A-d = ["select_mode", "goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
tab = "buffer_picker"
s = "goto_word"
W =  "@miW" # Select Whole word under cursor
w =  "@miw" # Select word under cursor
X = "select_line_above"
x = "select_line_below" 
d = "delete_selection_noyank"
c = "change_selection_noyank"
C = "copy_selection_on_next_line"
D = "copy_selection_on_prev_line"
C-s = ":w!" 
C-c = ["toggle_comments", "move_line_down"]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "@15zj"
C-k = "@15zk"
t = "expand_selection"
T = "shrink_selection"
C-f = "repeat_last_motion"
"C-." = "signature_help"
"," = "remove_primary_selection"

[keys.normal.space]
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
space = "@ y /<C-r>+"  # Global search word under cursor
x = ":yank-diagnostic"
z = "@\"%p\"+yd" # Copy buffer (repository relative) path in clipboard  
Z = "@o<esc>|pwd<ret>;i/<esc>\"%PmiW\"+yddk" # Copy buffer full-path in clipboard  
q = ":buffer-close!"
";" = "flip_selections"

[keys.select.m]
f = "select_regex"
F = "split_selection"
x = "join_selections"

[keys.select]
A-f = ["goto_line_end", "extend_line_below", "delete_selection", "paste_after", "select_mode" ]
A-d = ["goto_line_end", "extend_line_below", "delete_selection", "move_line_up", "paste_before", "select_mode"]
C-s = ["normal_mode", ":w!"] # Save file
X = "select_line_above"
x = "select_line_below"
d = "delete_selection_noyank"
c = "change_selection_noyank"
W =  "@miW" # Select Whole word under cursor
w =  "@miw" # Select word under cursor
s = "extend_to_word"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "@<esc>15zj"
C-k = "@<esc>15zk"
"," = "remove_primary_selection"

[keys.select.space]
";" = "flip_selections"

[keys.insert]
A-t = ["normal_mode", ":wqa!"]
A-b = ["normal_mode", ":qa!"]
C-s = ["normal_mode", ":w!"] 
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "@<esc>15zj"
C-k = "@<esc>15zk"
"C-." = "signature_help"
