theme = "max_monokai_pro_spectrum"
# theme = "catppuccin_latte"

[editor]
cursorline = true
mouse = true
true-color = true
scrolloff = 20 
auto-format = true
line-number = "relative"
auto-save = true
gutters = ["diagnostics", "spacer", "diff"]
jump-label-alphabet = "asdflkjureiwoqpvcbnty"
completion-timeout = 0
completion-trigger-len = 0

[editor.smart-tab]
enable = true

[editor.auto-pairs]
# '(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.soft-wrap]
enable = true

[editor.search]
wrap-around = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
right = [ "position", "position-percentage", "total-line-numbers", "selections"]
center = [ "file-name", "separator", "version-control" ]
left = [ "mode", "spinner", "diagnostics" ]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = " │ "

[keys.normal]
A-down = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]
A-up = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
C-s = ["normal_mode", ":w" ] # Save file
f = "goto_word"
F = "save_selection"
"\\" = "file_picker"
tab = "buffer_picker"
W =  "@miw<A-c>" # Change word under cursor
w =  "@miw"      # Select word under cursor
X = "select_line_above"
x = "select_line_below" 
t = "find_next_char"
T = "find_prev_char"
C-t = ":toggle file-picker.git-ignore"
C-q = ":buffer-close!"
C-c = ["toggle_comments", "move_line_down"]
"C-;" = "flip_selections"
"C-," = "remove_primary_selection"
d = "delete_selection_noyank"
c = "change_selection_noyank"
D = "copy_selection_on_prev_line"

[keys.normal."["]
"[" = "shrink_selection"

[keys.normal."]"]
"]" = "expand_selection"

[keys.normal.space]
t = "@ /%p <C-r>% %n " # Open string search on current buffer
z = "@\"%p\"+yd"        # Copy buffer path in clipboard  

[keys.select]
A-down = ["goto_line_end", "extend_line_below", "delete_selection", "paste_after", "select_mode" ]
A-up = ["goto_line_end", "extend_line_below", "delete_selection", "move_line_up", "paste_before", "select_mode"]
C-s = ["normal_mode", ":w"] # Save file
f = "extend_to_word"
X = "select_line_above"
x = "select_line_below"
t = "extend_next_char"
T = "extend_prev_char"
"C-;" = "flip_selections"
d = "delete_selection_noyank"
c = "change_selection_noyank"

[keys.insert]
C-s = ["normal_mode", ":w"] # Save file
