theme = "max_monokai_pro_spectrum_no_underline"
# theme = "max_catppuccin_latte"

[editor]
cursorline = true
mouse = true
true-color = true
scrolloff = 17 
auto-format = true
# line-number = "relative"
auto-save = true
gutters = ["diff","diagnostics", "line-numbers", "spacer"]
# gutters = ["diff","diagnostics", "spacer"]
jump-label-alphabet = "dlavmcfeiruwotybns;jk234789"
completion-timeout = 0
completion-trigger-len = 1
auto-pairs = false
bufferline = "never"

[editor.lsp]
auto-signature-help = false

[editor.inline-diagnostics]
# cursor-line = "hint"
cursor-line = "disable"

[editor.smart-tab]
enable = true
supersede-menu = true

# [editor.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# '`' = '`'
# '<' = '>'

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
# ignore = false
git-ignore = false
# git-global = false
git-exclude = false

[editor.indent-guides]
render = true

[editor.statusline]
right = [ "spinner", "position" ]
center = [ "file-name" ]
left = [ "mode" ]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = " │ "

[keys.normal]
A-t = ":wqa!"
A-b = ":qa!"
esc = ["collapse_selection", "keep_primary_selection"]
C-f = ["select_mode", "goto_line_end","extend_line_below", "delete_selection", "paste_after"]
C-d = ["select_mode", "goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
tab = "buffer_picker"
s = "goto_word"
W =  "@miW" # Select Whole word under cursor
w =  "@miw" # Select word under cursor
X = "select_line_above"
x = "select_line_below" 
d = "delete_selection_noyank"
c = "change_selection_noyank"
C = "copy_selection_on_next_line"
D = "copy_selection_on_prev_line"
t = "expand_selection"
T = "shrink_selection"
C-s = ":w!" 
C-q = ":buffer-close!"
C-c = ["toggle_comments", "move_line_down"]
C-j = "@15zj" # Scroll down
C-k = "@15zk" # Scroll up
C-h = "rotate_view_reverse"
C-l = "rotate_view"
J = "@]ff;<esc>"
K = "@[f<esc>"
H = "goto_previous_buffer"
L = "goto_next_buffer"
"C-." = "signature_help"

[keys.normal.f]
# "w" = "@ s%kind function %name "
"/" = "@ y /<C-r>+"  # Global search word under cursor
b = "@ /%p <C-r>% %n "  # Open string search on current buffer (with relative path)
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
r = "@:reload-all<ret>"
";" = "flip_selections"
"," = "remove_primary_selection"
t = ":toggle file-picker.git-ignore"
o = "jump_backward"
i = "jump_forward"
y = ":yank-diagnostic"
z = "@\"%p\"+yd" # Copy buffer (repository relative) path in clipboard  
Z = "@o<esc>|pwd<ret>;i/<esc>\"%PmiW\"+yddk" # Copy buffer full-path in clipboard  
d = "buffer_picker"
s = "file_picker"
a = "symbol_picker"
q = ":buffer-close!"
v = "vsplit"
x = "wclose"
h = "find_prev_char"
j = "till_prev_char"
k = "find_till_char"
l = "find_next_char"
f = "repeat_last_motion"

[keys.normal.space]
space = "file_picker"

[keys.normal.m]
f = "select_regex"
F = "split_selection"
x = "join_selections"

[keys.select.m]
f = "select_regex"
F = "split_selection"
x = "join_selections"


[keys.select]
C-f = ["goto_line_end", "extend_line_below", "delete_selection", "paste_after", "select_mode" ]
C-d = ["goto_line_end", "extend_line_below", "delete_selection", "move_line_up", "paste_before", "select_mode"]
C-s = ["normal_mode", ":w!"] # Save file
X = "select_line_above"
x = "select_line_below"
d = "delete_selection_noyank"
c = "change_selection_noyank"
W =  "@miW" # Select Whole word under cursor
w =  "@miw" # Select word under cursor
s = "extend_to_word"
C-j = "@15zj" # Scroll down
C-k = "@15zk" # Scroll up
C-h = "@15h"
C-l = "@15l"

[keys.select.f]
";" = "flip_selections"

[keys.insert]
A-t = ["normal_mode", ":wqa!"]
A-b = ["normal_mode", ":qa!"]
C-s = ["normal_mode", ":w!"] 
C-j = "@<esc>15zj" # Scroll down
C-k = "@<esc>15zk" # Scroll up
C-h = "rotate_view_reverse"
C-l = "rotate_view"
C-left = "@<esc>15hi"
C-right = "@<esc>15li"
"C-." = "signature_help"
