theme = "max_monokai_pro_spectrum"
# theme = "catppuccin_latte"

[editor]
cursorline = true
mouse = true
true-color = true
scrolloff = 17 
auto-format = true
line-number = "relative"
auto-save = true
gutters = ["diff","diagnostics", "line-numbers", "spacer"]
jump-label-alphabet = "fjdksla;vmc,x.eiruwotybn"
completion-timeout = 0
completion-trigger-len = 0

[editor.smart-tab]
enable = true

[editor.auto-pairs]
# '(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
right = [ "position", "position-percentage", "total-line-numbers", "selections"]
center = [ "file-name", "separator", "version-control" ]
left = [ "mode", "spinner", "diagnostics" ]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = " │ "

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-down = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]
A-up = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
C-s = ["normal_mode", ":w" ] # Save file
tab = "buffer_picker"
S-tab = "file_picker"
W =  "@miw<A-c>" # Change word under cursor
w =  "@miw"      # Select word under cursor
X = "select_line_above"
x = "select_line_below" 
t = "find_next_char"
T = "find_prev_char"
C-t = ":toggle file-picker.git-ignore"
C-q = ":buffer-close!"
C-c = ["toggle_comments", "move_line_down"]
"C-;" = "flip_selections"
"C-," = "remove_primary_selection"
d = "delete_selection_noyank"
c = "change_selection_noyank"
D = "copy_selection_on_prev_line"
";" = "symbol_picker"  # Open string search on current buffer
"\\" = "@ /%p <C-r>% %n "  # Open string search on current buffer
"C-j" = "@3zj"
"C-k" = "@3zk"
"J" = "goto_next_function"
"K" = "goto_prev_function"
"A-j" = "join_selections"

[keys.normal.space]
z = "@\"%p\"+yd" # Copy buffer path in clipboard  
space = "save_selection"

[keys.normal."["]
"[" = "shrink_selection"

[keys.normal."]"]
"]" = "expand_selection"

[keys.select]
A-down = ["goto_line_end", "extend_line_below", "delete_selection", "paste_after", "select_mode" ]
A-up = ["goto_line_end", "extend_line_below", "delete_selection", "move_line_up", "paste_before", "select_mode"]
C-s = ["normal_mode", ":w"] # Save file
X = "select_line_above"
x = "select_line_below"
"C-;" = "flip_selections"
d = "delete_selection_noyank"
c = "change_selection_noyank"
W =  "@miw<A-c>" # Change word under cursor
w =  "@miw"      # Select word under cursor

[keys.insert]
C-s = ["normal_mode", ":w"] # Save file
