theme = "monokai_pro_spectrum"

[editor]
cursorline = true
mouse = true
true-color = true
scrolloff = 15 
auto-format = true
line-number = "relative"
auto-save = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = " │ "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"C-s" = ["normal_mode", "commit_undo_checkpoint", ":w"]
"A-up" = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
"A-down" = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]
"f" = ["goto_word"]
"tab" = ["goto_next_buffer"]
"S-tab" = ["goto_previous_buffer"]
"C-q" = [":buffer-close"]
"C-h" = ["jump_view_left"]
"C-l" = ["jump_view_right"]

[keys.select]
"C-s" = ["normal_mode", "commit_undo_checkpoint", ":w"]
"A-up" = ["goto_line_end", "extend_line_below", "delete_selection", "move_line_up", "paste_before", "select_mode"]
"A-down" = ["goto_line_end", "extend_line_below", "delete_selection", "paste_after", "select_mode" ]
"f" = ["goto_word"]

[keys.insert]
"C-s" = ["normal_mode", "commit_undo_checkpoint", ":w"]
