theme = "monokai_pro_spectrum"

[editor]
cursorline = true
mouse = true
true-color = true
scrolloff = 15 
auto-format = true
line-number = "relative"
auto-save = true
gutters = ["diagnostics", "spacer", "diff"]
jump-label-alphabet = "asdflkjureiwoqpvcbnty"
completion-timeout = 0
completion-trigger-len = 0

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
right = [ "position", "position-percentage", "total-line-numbers", "selections"]
center = [ "file-name", "separator", "version-control" ]
left = [ "mode", "spinner", "diagnostics" ]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = " │ "

[keys.normal]
"A-down" = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]
"A-up" = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"C-q" = ":buffer-close"
"C-s" = ["normal_mode", "commit_undo_checkpoint", ":w"]
"f" = "goto_word"
"S-tab" = "goto_last_accessed_file"
"tab" = "buffer_picker"
"X" = "select_line_above"
"x" = "select_line_below"

[keys.select]
"A-down" = ["goto_line_end", "extend_line_below", "delete_selection", "paste_after", "select_mode" ]
"A-up" = ["goto_line_end", "extend_line_below", "delete_selection", "move_line_up", "paste_before", "select_mode"]
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"C-s" = ["normal_mode", "commit_undo_checkpoint", ":w"]
"f" = "extend_to_word"
"X" = "select_line_above"
"x" = "select_line_below"

[keys.insert]
"C-h" = ["normal_mode", "jump_view_left"]
"C-j" = ["normal_mode", "jump_view_down"]
"C-k" = ["normal_mode", "jump_view_up"]
"C-l" = ["normal_mode", "jump_view_right"]
"C-s" = ["normal_mode", "commit_undo_checkpoint", ":w"]

# TIPS
# copy the current buffer-path: "%P"+d
